esphome:
  name: espectre
  friendly_name: ESPectre
  min_version: 2025.11.0
  platformio_options:
    board_build.flash_mode: dio
    board_build.mcu: esp32c3
  project:
    name: francescopace.espectre
    version: "2.3.0-dev"

esp32:
  board: airm2m_core_esp32c3
  variant: ESP32C3
  framework:
    type: esp-idf
    #version: 5.5.1
    sdkconfig_options:
      # Power Management (critical for CSI reliability)
      CONFIG_PM_ENABLE: n                             # Disable all power management
      CONFIG_ESP_WIFI_STA_DISCONNECTED_PM_ENABLE: n   # No power save when disconnected
      # CSI Feature
      CONFIG_ESP_WIFI_CSI_ENABLED: y                  # Enable CSI extraction from WiFi packets

# Load ESPectre component from GitHub
external_components:
  - source:
      type: git
      url: https://github.com/francescopace/espectre
      ref: develop #git commit_hash or branch
    components: [ espectre ]
    refresh: always

# ESPectre - WiFi CSI Motion Detection
# Note: For Super Mini boards, keep traffic_generator_rate <= 94
espectre:
  id: espectre_csi
  # Motion detection
  traffic_generator_rate: 94   # Packets/sec for CSI generation (0-1000)
  traffic_generator_mode: dns  # dns (default) or ping
  segmentation_threshold: 1.0   # Motion sensitivity (default: 1.0)
  segmentation_window_size: 50  # Analysis window size in packets (10-200)
  # Low-pass filter (noise reduction)
  lowpass_enabled: false        # Enable low-pass filter (default: false)
  lowpass_cutoff: 11.0          # Cutoff frequency in Hz (5.0-20.0)
  # Gain lock mode: auto (default), enabled, or disabled
  gain_lock: auto              # auto (default), enabled, disabled
  # Hampel filter (anti-spikes in turbulence)
  hampel_enabled: false         # Enable outlier removal filter (default: false)
  hampel_window: 7              # Filter window size (3-11, odd numbers)
  hampel_threshold: 4.0         # Outlier detection threshold (1.0-10.0)
  # Subcarrier selection (optional - leave commented for auto-calibration at boot)
  # selected_subcarriers: [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]

web_server:
  port: 80
# WiFi with fallback AP for provisioning
wifi:
#  networks:
#    - ssid: !secret wifi_ssid
#      password: !secret wifi_password
#      #bssid: !secret wifi_bssid  # Lock to specific Access Point (useful for mesh networks)
  ap:
    ssid: "ESPectre Fallback"

captive_portal:

# Improv provisioning via BLE
#esp32_improv:
#  authorizer: none

# Improv provisioning via USB
#improv_serial:

# Logging
logger:
  baud_rate: 115200
  hardware_uart: UART0
  level: DEBUG #VERBOSE
  logs:
    sensor: INFO
    binary_sensor: INFO

# Home Assistant API
api:

# OTA updates
ota:
  - platform: esphome
    password: "123456"

debug:
  update_interval: 5s

sensor:
  - platform: debug
    free:
      name: "Free Heap"
    block:
      name: "Max Free Block"
    loop_time:
      name: "Loop Time"

text_sensor:
  - platform: debug
    device:
      name: "Device Info"
    reset_reason:
      name: "Reset Reason"